import sys
from source.ui.map_generator import Ui_MainWindow
from source.ui import map_generator

from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtWidgets
from PyQt5.QtCore import QCoreApplication

types = {0: "Start", 1: "Finish", 2: "Simple", 3: "Coloration", 4: "Color check", 5: "Clear"}
colors = {0: "yellow", 1: "red", 2: "gray", 3: "blue", 4: "darkBlue", 5: "#e1e1e1"}


class Object:
    def __init__(self, x, y, obj_type):
        self.x = x
        self.y = y
        self.type = obj_type

    def check_match(self, x, y):
        if self.x == x and self.y == y:
            return True
        else:
            return False

    def __str__(self):
        return str("(" + str(self.type) + ", new Vector3(" + str(self.x) + ",-5," + str(self.y) + "))")


## Class for main application window
class MainWindow(QtWidgets.QMainWindow, map_generator.Ui_MainWindow):  # poker_gui.Ui_MainWindow
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.data = {}
        self.text_data = ""
        self.current_type = None

        self.connect_all_btns()
        self.connect_all_radios()
        self.ui.btn_generate.clicked.connect(self.generate_script)
        self.ui.btn_clear.clicked.connect(self.clear)
        self.ui.btn_save_to_txt.clicked.connect(self.save_to_txt)

    def connect_all_radios(self):
        self.ui.radio_empty.toggled.connect(self.radio_toddled)
        self.ui.radio_finish.toggled.connect(self.radio_toddled)
        self.ui.radio_simple.toggled.connect(self.radio_toddled)
        self.ui.radio_start.toggled.connect(self.radio_toddled)
        self.ui.radio_color_check.toggled.connect(self.radio_toddled)
        self.ui.radio_coloration.toggled.connect(self.radio_toddled)

        self.ui.radio_start.id = 0
        self.ui.radio_finish.id = 1
        self.ui.radio_simple.id = 2
        self.ui.radio_coloration.id = 3
        self.ui.radio_color_check.id = 4
        self.ui.radio_empty.id = 5

    def connect_all_btns(self):
        # Auto-generated
        self.ui.pushButton.clicked.connect(self.platform_clicked)
        self.ui.pushButton.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_270.clicked.connect(self.platform_clicked)
        self.ui.pushButton_270.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_155.clicked.connect(self.platform_clicked)
        self.ui.pushButton_155.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_183.clicked.connect(self.platform_clicked)
        self.ui.pushButton_183.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_109.clicked.connect(self.platform_clicked)
        self.ui.pushButton_109.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_168.clicked.connect(self.platform_clicked)
        self.ui.pushButton_168.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_104.clicked.connect(self.platform_clicked)
        self.ui.pushButton_104.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_44.clicked.connect(self.platform_clicked)
        self.ui.pushButton_44.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_108.clicked.connect(self.platform_clicked)
        self.ui.pushButton_108.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_181.clicked.connect(self.platform_clicked)
        self.ui.pushButton_181.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_28.clicked.connect(self.platform_clicked)
        self.ui.pushButton_28.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_148.clicked.connect(self.platform_clicked)
        self.ui.pushButton_148.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_230.clicked.connect(self.platform_clicked)
        self.ui.pushButton_230.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_79.clicked.connect(self.platform_clicked)
        self.ui.pushButton_79.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_189.clicked.connect(self.platform_clicked)
        self.ui.pushButton_189.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_147.clicked.connect(self.platform_clicked)
        self.ui.pushButton_147.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_200.clicked.connect(self.platform_clicked)
        self.ui.pushButton_200.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_224.clicked.connect(self.platform_clicked)
        self.ui.pushButton_224.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_11.clicked.connect(self.platform_clicked)
        self.ui.pushButton_11.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_24.clicked.connect(self.platform_clicked)
        self.ui.pushButton_24.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_89.clicked.connect(self.platform_clicked)
        self.ui.pushButton_89.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_19.clicked.connect(self.platform_clicked)
        self.ui.pushButton_19.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_8.clicked.connect(self.platform_clicked)
        self.ui.pushButton_8.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_20.clicked.connect(self.platform_clicked)
        self.ui.pushButton_20.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_180.clicked.connect(self.platform_clicked)
        self.ui.pushButton_180.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_114.clicked.connect(self.platform_clicked)
        self.ui.pushButton_114.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_37.clicked.connect(self.platform_clicked)
        self.ui.pushButton_37.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_136.clicked.connect(self.platform_clicked)
        self.ui.pushButton_136.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_76.clicked.connect(self.platform_clicked)
        self.ui.pushButton_76.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_16.clicked.connect(self.platform_clicked)
        self.ui.pushButton_16.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_153.clicked.connect(self.platform_clicked)
        self.ui.pushButton_153.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_234.clicked.connect(self.platform_clicked)
        self.ui.pushButton_234.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_220.clicked.connect(self.platform_clicked)
        self.ui.pushButton_220.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_129.clicked.connect(self.platform_clicked)
        self.ui.pushButton_129.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_83.clicked.connect(self.platform_clicked)
        self.ui.pushButton_83.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_174.clicked.connect(self.platform_clicked)
        self.ui.pushButton_174.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_7.clicked.connect(self.platform_clicked)
        self.ui.pushButton_7.setStyleSheet("color: #e1e1e1;")
        self.ui.p00.clicked.connect(self.platform_clicked)
        self.ui.p00.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_150.clicked.connect(self.platform_clicked)
        self.ui.pushButton_150.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_203.clicked.connect(self.platform_clicked)
        self.ui.pushButton_203.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_35.clicked.connect(self.platform_clicked)
        self.ui.pushButton_35.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_173.clicked.connect(self.platform_clicked)
        self.ui.pushButton_173.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_103.clicked.connect(self.platform_clicked)
        self.ui.pushButton_103.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_227.clicked.connect(self.platform_clicked)
        self.ui.pushButton_227.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_100.clicked.connect(self.platform_clicked)
        self.ui.pushButton_100.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_23.clicked.connect(self.platform_clicked)
        self.ui.pushButton_23.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_121.clicked.connect(self.platform_clicked)
        self.ui.pushButton_121.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_49.clicked.connect(self.platform_clicked)
        self.ui.pushButton_49.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_139.clicked.connect(self.platform_clicked)
        self.ui.pushButton_139.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_41.clicked.connect(self.platform_clicked)
        self.ui.pushButton_41.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_137.clicked.connect(self.platform_clicked)
        self.ui.pushButton_137.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_63.clicked.connect(self.platform_clicked)
        self.ui.pushButton_63.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_198.clicked.connect(self.platform_clicked)
        self.ui.pushButton_198.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_86.clicked.connect(self.platform_clicked)
        self.ui.pushButton_86.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_178.clicked.connect(self.platform_clicked)
        self.ui.pushButton_178.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_223.clicked.connect(self.platform_clicked)
        self.ui.pushButton_223.setStyleSheet("color: #e1e1e1;")
        self.ui.p20.clicked.connect(self.platform_clicked)
        self.ui.p20.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_176.clicked.connect(self.platform_clicked)
        self.ui.pushButton_176.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_113.clicked.connect(self.platform_clicked)
        self.ui.pushButton_113.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_131.clicked.connect(self.platform_clicked)
        self.ui.pushButton_131.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_171.clicked.connect(self.platform_clicked)
        self.ui.pushButton_171.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_151.clicked.connect(self.platform_clicked)
        self.ui.pushButton_151.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_107.clicked.connect(self.platform_clicked)
        self.ui.pushButton_107.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_190.clicked.connect(self.platform_clicked)
        self.ui.pushButton_190.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_167.clicked.connect(self.platform_clicked)
        self.ui.pushButton_167.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_21.clicked.connect(self.platform_clicked)
        self.ui.pushButton_21.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_58.clicked.connect(self.platform_clicked)
        self.ui.pushButton_58.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_14.clicked.connect(self.platform_clicked)
        self.ui.pushButton_14.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_55.clicked.connect(self.platform_clicked)
        self.ui.pushButton_55.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_225.clicked.connect(self.platform_clicked)
        self.ui.pushButton_225.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_226.clicked.connect(self.platform_clicked)
        self.ui.pushButton_226.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_144.clicked.connect(self.platform_clicked)
        self.ui.pushButton_144.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_243.clicked.connect(self.platform_clicked)
        self.ui.pushButton_243.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_119.clicked.connect(self.platform_clicked)
        self.ui.pushButton_119.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_96.clicked.connect(self.platform_clicked)
        self.ui.pushButton_96.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_235.clicked.connect(self.platform_clicked)
        self.ui.pushButton_235.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_156.clicked.connect(self.platform_clicked)
        self.ui.pushButton_156.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_69.clicked.connect(self.platform_clicked)
        self.ui.pushButton_69.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_110.clicked.connect(self.platform_clicked)
        self.ui.pushButton_110.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_132.clicked.connect(self.platform_clicked)
        self.ui.pushButton_132.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_71.clicked.connect(self.platform_clicked)
        self.ui.pushButton_71.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_27.clicked.connect(self.platform_clicked)
        self.ui.pushButton_27.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_102.clicked.connect(self.platform_clicked)
        self.ui.pushButton_102.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_67.clicked.connect(self.platform_clicked)
        self.ui.pushButton_67.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_146.clicked.connect(self.platform_clicked)
        self.ui.pushButton_146.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_149.clicked.connect(self.platform_clicked)
        self.ui.pushButton_149.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_124.clicked.connect(self.platform_clicked)
        self.ui.pushButton_124.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_78.clicked.connect(self.platform_clicked)
        self.ui.pushButton_78.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_54.clicked.connect(self.platform_clicked)
        self.ui.pushButton_54.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_228.clicked.connect(self.platform_clicked)
        self.ui.pushButton_228.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_120.clicked.connect(self.platform_clicked)
        self.ui.pushButton_120.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_245.clicked.connect(self.platform_clicked)
        self.ui.pushButton_245.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_212.clicked.connect(self.platform_clicked)
        self.ui.pushButton_212.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_160.clicked.connect(self.platform_clicked)
        self.ui.pushButton_160.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_134.clicked.connect(self.platform_clicked)
        self.ui.pushButton_134.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_34.clicked.connect(self.platform_clicked)
        self.ui.pushButton_34.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_13.clicked.connect(self.platform_clicked)
        self.ui.pushButton_13.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_82.clicked.connect(self.platform_clicked)
        self.ui.pushButton_82.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_133.clicked.connect(self.platform_clicked)
        self.ui.pushButton_133.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_111.clicked.connect(self.platform_clicked)
        self.ui.pushButton_111.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_218.clicked.connect(self.platform_clicked)
        self.ui.pushButton_218.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_68.clicked.connect(self.platform_clicked)
        self.ui.pushButton_68.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_80.clicked.connect(self.platform_clicked)
        self.ui.pushButton_80.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_145.clicked.connect(self.platform_clicked)
        self.ui.pushButton_145.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_105.clicked.connect(self.platform_clicked)
        self.ui.pushButton_105.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_50.clicked.connect(self.platform_clicked)
        self.ui.pushButton_50.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_52.clicked.connect(self.platform_clicked)
        self.ui.pushButton_52.setStyleSheet("color: #e1e1e1;")
        self.ui.p40.clicked.connect(self.platform_clicked)
        self.ui.p40.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_182.clicked.connect(self.platform_clicked)
        self.ui.pushButton_182.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_101.clicked.connect(self.platform_clicked)
        self.ui.pushButton_101.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_187.clicked.connect(self.platform_clicked)
        self.ui.pushButton_187.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_249.clicked.connect(self.platform_clicked)
        self.ui.pushButton_249.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_142.clicked.connect(self.platform_clicked)
        self.ui.pushButton_142.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_122.clicked.connect(self.platform_clicked)
        self.ui.pushButton_122.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_141.clicked.connect(self.platform_clicked)
        self.ui.pushButton_141.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_164.clicked.connect(self.platform_clicked)
        self.ui.pushButton_164.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_47.clicked.connect(self.platform_clicked)
        self.ui.pushButton_47.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_163.clicked.connect(self.platform_clicked)
        self.ui.pushButton_163.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_162.clicked.connect(self.platform_clicked)
        self.ui.pushButton_162.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_12.clicked.connect(self.platform_clicked)
        self.ui.pushButton_12.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_39.clicked.connect(self.platform_clicked)
        self.ui.pushButton_39.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_57.clicked.connect(self.platform_clicked)
        self.ui.pushButton_57.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_10.clicked.connect(self.platform_clicked)
        self.ui.pushButton_10.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_157.clicked.connect(self.platform_clicked)
        self.ui.pushButton_157.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_135.clicked.connect(self.platform_clicked)
        self.ui.pushButton_135.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_94.clicked.connect(self.platform_clicked)
        self.ui.pushButton_94.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_18.clicked.connect(self.platform_clicked)
        self.ui.pushButton_18.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_95.clicked.connect(self.platform_clicked)
        self.ui.pushButton_95.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_152.clicked.connect(self.platform_clicked)
        self.ui.pushButton_152.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_258.clicked.connect(self.platform_clicked)
        self.ui.pushButton_258.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_74.clicked.connect(self.platform_clicked)
        self.ui.pushButton_74.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_172.clicked.connect(self.platform_clicked)
        self.ui.pushButton_172.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_169.clicked.connect(self.platform_clicked)
        self.ui.pushButton_169.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_32.clicked.connect(self.platform_clicked)
        self.ui.pushButton_32.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_91.clicked.connect(self.platform_clicked)
        self.ui.pushButton_91.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_126.clicked.connect(self.platform_clicked)
        self.ui.pushButton_126.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_247.clicked.connect(self.platform_clicked)
        self.ui.pushButton_247.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_42.clicked.connect(self.platform_clicked)
        self.ui.pushButton_42.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_123.clicked.connect(self.platform_clicked)
        self.ui.pushButton_123.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_161.clicked.connect(self.platform_clicked)
        self.ui.pushButton_161.setStyleSheet("color: #e1e1e1;")
        self.ui.p10_2.clicked.connect(self.platform_clicked)
        self.ui.p10_2.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_118.clicked.connect(self.platform_clicked)
        self.ui.pushButton_118.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_179.clicked.connect(self.platform_clicked)
        self.ui.pushButton_179.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_85.clicked.connect(self.platform_clicked)
        self.ui.pushButton_85.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_77.clicked.connect(self.platform_clicked)
        self.ui.pushButton_77.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_241.clicked.connect(self.platform_clicked)
        self.ui.pushButton_241.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_84.clicked.connect(self.platform_clicked)
        self.ui.pushButton_84.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_177.clicked.connect(self.platform_clicked)
        self.ui.pushButton_177.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_93.clicked.connect(self.platform_clicked)
        self.ui.pushButton_93.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_73.clicked.connect(self.platform_clicked)
        self.ui.pushButton_73.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_239.clicked.connect(self.platform_clicked)
        self.ui.pushButton_239.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_4.clicked.connect(self.platform_clicked)
        self.ui.pushButton_4.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_2.clicked.connect(self.platform_clicked)
        self.ui.pushButton_2.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_6.clicked.connect(self.platform_clicked)
        self.ui.pushButton_6.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_53.clicked.connect(self.platform_clicked)
        self.ui.pushButton_53.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_90.clicked.connect(self.platform_clicked)
        self.ui.pushButton_90.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_43.clicked.connect(self.platform_clicked)
        self.ui.pushButton_43.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_3.clicked.connect(self.platform_clicked)
        self.ui.pushButton_3.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_106.clicked.connect(self.platform_clicked)
        self.ui.pushButton_106.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_81.clicked.connect(self.platform_clicked)
        self.ui.pushButton_81.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_88.clicked.connect(self.platform_clicked)
        self.ui.pushButton_88.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_45.clicked.connect(self.platform_clicked)
        self.ui.pushButton_45.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_31.clicked.connect(self.platform_clicked)
        self.ui.pushButton_31.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_191.clicked.connect(self.platform_clicked)
        self.ui.pushButton_191.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_65.clicked.connect(self.platform_clicked)
        self.ui.pushButton_65.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_166.clicked.connect(self.platform_clicked)
        self.ui.pushButton_166.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_264.clicked.connect(self.platform_clicked)
        self.ui.pushButton_264.setStyleSheet("color: #e1e1e1;")
        self.ui.p20_2.clicked.connect(self.platform_clicked)
        self.ui.p20_2.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_165.clicked.connect(self.platform_clicked)
        self.ui.pushButton_165.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_64.clicked.connect(self.platform_clicked)
        self.ui.pushButton_64.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_244.clicked.connect(self.platform_clicked)
        self.ui.pushButton_244.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_115.clicked.connect(self.platform_clicked)
        self.ui.pushButton_115.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_98.clicked.connect(self.platform_clicked)
        self.ui.pushButton_98.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_116.clicked.connect(self.platform_clicked)
        self.ui.pushButton_116.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_46.clicked.connect(self.platform_clicked)
        self.ui.pushButton_46.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_117.clicked.connect(self.platform_clicked)
        self.ui.pushButton_117.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_222.clicked.connect(self.platform_clicked)
        self.ui.pushButton_222.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_9.clicked.connect(self.platform_clicked)
        self.ui.pushButton_9.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_62.clicked.connect(self.platform_clicked)
        self.ui.pushButton_62.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_112.clicked.connect(self.platform_clicked)
        self.ui.pushButton_112.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_30.clicked.connect(self.platform_clicked)
        self.ui.pushButton_30.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_154.clicked.connect(self.platform_clicked)
        self.ui.pushButton_154.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_70.clicked.connect(self.platform_clicked)
        self.ui.pushButton_70.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_175.clicked.connect(self.platform_clicked)
        self.ui.pushButton_175.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_72.clicked.connect(self.platform_clicked)
        self.ui.pushButton_72.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_130.clicked.connect(self.platform_clicked)
        self.ui.pushButton_130.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_29.clicked.connect(self.platform_clicked)
        self.ui.pushButton_29.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_127.clicked.connect(self.platform_clicked)
        self.ui.pushButton_127.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_231.clicked.connect(self.platform_clicked)
        self.ui.pushButton_231.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_128.clicked.connect(self.platform_clicked)
        self.ui.pushButton_128.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_26.clicked.connect(self.platform_clicked)
        self.ui.pushButton_26.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_25.clicked.connect(self.platform_clicked)
        self.ui.pushButton_25.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_170.clicked.connect(self.platform_clicked)
        self.ui.pushButton_170.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_92.clicked.connect(self.platform_clicked)
        self.ui.pushButton_92.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_51.clicked.connect(self.platform_clicked)
        self.ui.pushButton_51.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_252.clicked.connect(self.platform_clicked)
        self.ui.pushButton_252.setStyleSheet("color: #e1e1e1;")
        self.ui.p10.clicked.connect(self.platform_clicked)
        self.ui.p10.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_202.clicked.connect(self.platform_clicked)
        self.ui.pushButton_202.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_66.clicked.connect(self.platform_clicked)
        self.ui.pushButton_66.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_40.clicked.connect(self.platform_clicked)
        self.ui.pushButton_40.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_87.clicked.connect(self.platform_clicked)
        self.ui.pushButton_87.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_48.clicked.connect(self.platform_clicked)
        self.ui.pushButton_48.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_56.clicked.connect(self.platform_clicked)
        self.ui.pushButton_56.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_22.clicked.connect(self.platform_clicked)
        self.ui.pushButton_22.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_186.clicked.connect(self.platform_clicked)
        self.ui.pushButton_186.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_99.clicked.connect(self.platform_clicked)
        self.ui.pushButton_99.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_143.clicked.connect(self.platform_clicked)
        self.ui.pushButton_143.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_38.clicked.connect(self.platform_clicked)
        self.ui.pushButton_38.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_158.clicked.connect(self.platform_clicked)
        self.ui.pushButton_158.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_140.clicked.connect(self.platform_clicked)
        self.ui.pushButton_140.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_15.clicked.connect(self.platform_clicked)
        self.ui.pushButton_15.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_97.clicked.connect(self.platform_clicked)
        self.ui.pushButton_97.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_17.clicked.connect(self.platform_clicked)
        self.ui.pushButton_17.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_159.clicked.connect(self.platform_clicked)
        self.ui.pushButton_159.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_237.clicked.connect(self.platform_clicked)
        self.ui.pushButton_237.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_138.clicked.connect(self.platform_clicked)
        self.ui.pushButton_138.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_263.clicked.connect(self.platform_clicked)
        self.ui.pushButton_263.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_60.clicked.connect(self.platform_clicked)
        self.ui.pushButton_60.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_207.clicked.connect(self.platform_clicked)
        self.ui.pushButton_207.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_33.clicked.connect(self.platform_clicked)
        self.ui.pushButton_33.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_61.clicked.connect(self.platform_clicked)
        self.ui.pushButton_61.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_5.clicked.connect(self.platform_clicked)
        self.ui.pushButton_5.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_36.clicked.connect(self.platform_clicked)
        self.ui.pushButton_36.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_75.clicked.connect(self.platform_clicked)
        self.ui.pushButton_75.setStyleSheet("color: #e1e1e1;")
        self.ui.pushButton_59.clicked.connect(self.platform_clicked)
        self.ui.pushButton_59.setStyleSheet("color: #e1e1e1;")

    def get_coords(self, btn_id):
        x = (btn_id - 1 )% 15
        y = (btn_id - 1) // 15
        return x, y

    def platform_clicked(self):
        sender = self.sender()
        btn_id = int(sender.text())

        # Get parameters
        coord_x, coord_y = self.get_coords(btn_id)
        obj_type = self.current_type

        if obj_type == None:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Type error")
            msg.setInformativeText('Yes, error, but what did you expect? You didn\'t even choose the type of platform')
            msg.setWindowTitle("Error")
            msg.exec_()
        else:
            if obj_type == 5:
                if str(coord_x) + ',' + str(coord_y) in self.data:
                    del self.data[str(coord_x) + ',' + str(coord_y)]
            else:
                # Add new object
                self.data[str(coord_x) + ',' + str(coord_y)] = Object(coord_x, coord_y, obj_type)
            color = colors[self.current_type]
            sender.setStyleSheet("background-color: " + color + "; color: " + color)

    def radio_toddled(self):
        sender = self.sender()
        if sender.isChecked():
            self.current_type = sender.id

    def generate_script(self):
        self.ui.output_text.clear()
        self.text_data += "public List<(int, Vector3)> ColumnCoords = new List<(int, Vector3)>(){ " + "\n"

        for obj in self.data.items():
            self.ui.output_text.addItem(str(obj[1]) + ",")
            self.text_data += str(obj[1]) + ",\n"

        self.text_data += "}\n"

    def clear(self):
        self.data = {}
        self.connect_all_btns()

    def save_to_txt(self):
        file = open('output_txt/text.txt', 'w')
        file.write("using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\n\npublic class "
                   "ColumnSpawnScript : MonoBehaviour{\npublic GameObject[] objects;\n")
        file.write(self.text_data)
        file.close()
        # Success message
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Saved successfully")
        msg.setInformativeText('Your script is now located in source/ouput_txt directory')
        msg.setWindowTitle("Saved")
        msg.exec_()


def run_application():
    # Application setup
    app = QtWidgets.QApplication(sys.argv)  # New QApplication
    window = MainWindow()  # Create MainWindow
    window.show()  # Show window

    app.exec()
